// Generated by gencpp from file comp0037_planner_controller/Goal.msg
// DO NOT EDIT!


#ifndef COMP0037_PLANNER_CONTROLLER_MESSAGE_GOAL_H
#define COMP0037_PLANNER_CONTROLLER_MESSAGE_GOAL_H

#include <ros/service_traits.h>


#include <comp0037_planner_controller/GoalRequest.h>
#include <comp0037_planner_controller/GoalResponse.h>


namespace comp0037_planner_controller
{

struct Goal
{

typedef GoalRequest Request;
typedef GoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goal
} // namespace comp0037_planner_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comp0037_planner_controller::Goal > {
  static const char* value()
  {
    return "b457b1c81af64c78b366c8737f41a06f";
  }

  static const char* value(const ::comp0037_planner_controller::Goal&) { return value(); }
};

template<>
struct DataType< ::comp0037_planner_controller::Goal > {
  static const char* value()
  {
    return "comp0037_planner_controller/Goal";
  }

  static const char* value(const ::comp0037_planner_controller::Goal&) { return value(); }
};


// service_traits::MD5Sum< ::comp0037_planner_controller::GoalRequest> should match 
// service_traits::MD5Sum< ::comp0037_planner_controller::Goal > 
template<>
struct MD5Sum< ::comp0037_planner_controller::GoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comp0037_planner_controller::Goal >::value();
  }
  static const char* value(const ::comp0037_planner_controller::GoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comp0037_planner_controller::GoalRequest> should match 
// service_traits::DataType< ::comp0037_planner_controller::Goal > 
template<>
struct DataType< ::comp0037_planner_controller::GoalRequest>
{
  static const char* value()
  {
    return DataType< ::comp0037_planner_controller::Goal >::value();
  }
  static const char* value(const ::comp0037_planner_controller::GoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comp0037_planner_controller::GoalResponse> should match 
// service_traits::MD5Sum< ::comp0037_planner_controller::Goal > 
template<>
struct MD5Sum< ::comp0037_planner_controller::GoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comp0037_planner_controller::Goal >::value();
  }
  static const char* value(const ::comp0037_planner_controller::GoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comp0037_planner_controller::GoalResponse> should match 
// service_traits::DataType< ::comp0037_planner_controller::Goal > 
template<>
struct DataType< ::comp0037_planner_controller::GoalResponse>
{
  static const char* value()
  {
    return DataType< ::comp0037_planner_controller::Goal >::value();
  }
  static const char* value(const ::comp0037_planner_controller::GoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMP0037_PLANNER_CONTROLLER_MESSAGE_GOAL_H
